apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactwebapp-deployment
  labels:
    app: reactwebapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reactwebapp
  template:
    metadata:
      labels:
        app: reactwebapp
    spec:
      containers:
        - name: reactwebapp
          image: omarimi/reactwebapp:latest
          ports:
            - containerPort: 9000

